/*
 * 將要隨機派發的網址放入下方（不需排序）
 *
 * 並請注意：
 * 1. 除最後一項外，其餘項目用逗號分隔
 * 2. 網址請用引號包起來
 */


const urls = [
	'https://forms.gle/WxwB5vn7kvwhW5GUA',
	'https://forms.gle/nLi72aturLvjnqucA',
	'https://forms.gle/tYcLerY5yZ4SLAdV6',
	'https://forms.gle/5BkDWcA57YazZb699',
	'https://forms.gle/TTFYWCCcuMf5ufgQA',
	'https://forms.gle/pjqG2EnieCa6WARK6',
	'https://forms.gle/FA4Jf4NiaznFYypr6',
	'https://forms.gle/gpJx5qfeeM6wSpPo7',
	'https://forms.gle/nCSVuA1yrz1mgGXA7',
	'https://forms.gle/3X3xdtSEHcFmRCMM9',
	'https://forms.gle/39zm1Fp1BYA6UbyR8',
	'https://forms.gle/Wi7Sio4Z4fH2FdNu9',
	'https://forms.gle/LckQX5TZ1mwfsL7z8',
	'https://forms.gle/VKL6Fe8xCfNzsWQv7',
	'https://forms.gle/xF9Av4yZC7w6Hgtq8',
	'https://forms.gle/krWodFpPheqTrv9F6',
	'https://forms.gle/tzZkybeWG9GWLWWWA',
	'https://forms.gle/gEknDq3CSiaagBZu7',
	'https://forms.gle/7G65vLeNKyJMTJHx8',
	'https://forms.gle/vczvrDnJYXj6VFcm9',
	'https://forms.gle/ihLqpgjph2EgArRL6',
	'https://forms.gle/Escws7rYgPfbUNKQ6',
	'https://forms.gle/vPMcqgcmN6pAZeUT6',
	'https://forms.gle/uFJH7RbTLzQnX5u26',
	'https://forms.gle/1NrvYNtS3o4e2qpR9',
	'https://forms.gle/P5diZnnfgkvouvbE7',
	'https://forms.gle/4pLBJXS2uFNCNbbu6',
	'https://forms.gle/XfzfNVD6AhZecUjw7',
	'https://forms.gle/SPZpeZLM44hmXCuM6',
	'https://forms.gle/rGriBwZ6gfYCJ9i9A',
	'https://forms.gle/gB7exzwkCEyR7dbn8',
	'https://forms.gle/jjMJvCCoyW8RvHRu5',
	'https://forms.gle/ooH6idL8efCkb6ZH7',
	'https://forms.gle/wAZxTXfEBk137Zcr7',
	'https://forms.gle/suTHTY7Njw54i2Ye8',
	'https://forms.gle/XsaYiY9PawqCkq3u5',
	'https://forms.gle/AQeRwDv5BZq5acK29',
	'https://forms.gle/NpHUVH87bPzjSfHx8',
	'https://forms.gle/2zdHMNFTXeEwUBku9',
	'https://forms.gle/mcxyFo73qyvpJysh7',
	'https://forms.gle/CxvKxoc53ZyGypq47',
	'https://forms.gle/KzvZw5cZoYje6YEG9',
	'https://forms.gle/VpnDPFWKQzF2fN7s7',
	'https://forms.gle/9BxnZoYLw9UaY7Gw7',
	'https://forms.gle/Tnwh8uC8DRr1EPxo8',
	'https://forms.gle/gpT28rZwijeDdFoG7',
	'https://forms.gle/GrWT4K44PVARX8TL6',
	'https://forms.gle/vJkGzgijnkCwTBf87',
	'https://forms.gle/stpTGfQ19ypW3ytQ6',
	'https://forms.gle/5TL29zLNUCqHLk4n6',
	'https://forms.gle/A34USbrN1139EpAk7',
	'https://forms.gle/1BCHdAhbi2DZFrc16',
	'https://forms.gle/2JjBtrcMDbkTj9Sa9',
	'https://forms.gle/T8PATnE1VhWymEh8A',
	'https://forms.gle/GGj3AxF7ep31UoMr9',
	'https://forms.gle/G5Fyq9qmaHhVAWwr9',
	'https://forms.gle/xXhbXz8vkGdTJnDQ6',
	'https://forms.gle/RgvZsBSfFHtHTJig7',
	'https://forms.gle/ZXQGxjGgpJ7BGcn96',
	'https://forms.gle/JLbovSTcFkoZQigN6',
	'https://forms.gle/Q6AFB68RA6PW3dqW6',
	'https://forms.gle/ENzSQo9DmdERDPbAA',
	'https://forms.gle/RkoS3V86Z75DDc7NA',
	'https://forms.gle/sF2eXasj1eZEUyRr7'
];
